name: pretest_flutterdev_nusantara_infrastructure
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0-1.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  flutter_smart_dialog: ^4.9.5+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - .env

